# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreaF.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Crear_Factura(object):
    def setupUi(self, Crear_Factura):
        Crear_Factura.setObjectName("Crear_Factura")
        Crear_Factura.resize(387, 350)
        self.centralwidget = QtWidgets.QWidget(Crear_Factura)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 60, 301, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Placa = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Placa.setObjectName("label_Placa")
        self.verticalLayout.addWidget(self.label_Placa)
        self.label_NoID = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_NoID.setObjectName("label_NoID")
        self.verticalLayout.addWidget(self.label_NoID)
        self.label_Service = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Service.setObjectName("label_Service")
        self.verticalLayout.addWidget(self.label_Service)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PLATE = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.PLATE.setObjectName("PLATE")
        self.verticalLayout_2.addWidget(self.PLATE)
        self.NOID = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.NOID.setObjectName("NOID")
        self.verticalLayout_2.addWidget(self.NOID)
        self.SERVICE = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.SERVICE.setObjectName("SERVICE")
        self.verticalLayout_2.addWidget(self.SERVICE)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 180, 195, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ButtonOK = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ButtonOK.setObjectName("ButtonOK")
        self.horizontalLayout_2.addWidget(self.ButtonOK)
        self.ButtonCANCELF = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ButtonCANCELF.setObjectName("ButtonCANCELF")
        self.horizontalLayout_2.addWidget(self.ButtonCANCELF)
        self.retranslateUi(Crear_Factura)
        self.ButtonCANCELF.clicked.connect(Crear_Factura.close)
        QtCore.QMetaObject.connectSlotsByName(Crear_Factura)
        Crear_Factura.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Crear_Factura)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 26))
        self.menubar.setObjectName("menubar")
        Crear_Factura.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Crear_Factura)
        self.statusbar.setObjectName("statusbar")
        Crear_Factura.setStatusBar(self.statusbar)

        self.retranslateUi(Crear_Factura)
        QtCore.QMetaObject.connectSlotsByName(Crear_Factura)

    def retranslateUi(self, Crear_Factura):
        _translate = QtCore.QCoreApplication.translate
        Crear_Factura.setWindowTitle(_translate("Crear_Factura", "MainWindow"))
        self.label_Placa.setText(_translate("Crear_Factura", "Placa"))
        self.label_NoID.setText(_translate("Crear_Factura", "Número de identificacion"))
        self.label_Service.setText(_translate("Crear_Factura", "Servicio"))
        self.ButtonOK.setText(_translate("Crear_Factura", "Aceptar"))
        self.ButtonCANCELF.setText(_translate("Crear_Factura", "Cancelar"))
