# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(60, 70, 91, 181))
        self.toolBox.setObjectName("toolBox")
        self.Clientes = QtWidgets.QWidget()
        self.Clientes.setGeometry(QtCore.QRect(0, 0, 91, 100))
        self.Clientes.setObjectName("Clientes")
        self.BotonBorrarC = QtWidgets.QPushButton(self.Clientes)
        self.BotonBorrarC.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.BotonBorrarC.setObjectName("BotonBorrarC")
        self.BotonCrearC = QtWidgets.QPushButton(self.Clientes)
        self.BotonCrearC.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.BotonCrearC.setObjectName("BotonCrearC")
        self.BotonListarC = QtWidgets.QPushButton(self.Clientes)
        self.BotonListarC.setGeometry(QtCore.QRect(0, 60, 91, 23))
        self.BotonListarC.setObjectName("BotonListarC")
        self.toolBox.addItem(self.Clientes, "")
        self.Vehiculos = QtWidgets.QWidget()
        self.Vehiculos.setGeometry(QtCore.QRect(0, 0, 91, 100))
        self.Vehiculos.setObjectName("Vehiculos")
        self.BotonCrearV = QtWidgets.QPushButton(self.Vehiculos)
        self.BotonCrearV.setGeometry(QtCore.QRect(0, 0, 81, 23))
        self.BotonCrearV.setObjectName("BotonCrearV")
        self.BotonBorrarV = QtWidgets.QPushButton(self.Vehiculos)
        self.BotonBorrarV.setGeometry(QtCore.QRect(0, 30, 81, 23))
        self.BotonBorrarV.setObjectName("BotonBorrarV")
        self.BotonListarV = QtWidgets.QPushButton(self.Vehiculos)
        self.BotonListarV.setGeometry(QtCore.QRect(0, 60, 91, 23))
        self.BotonListarV.setObjectName("BotonListarV")
        self.toolBox.addItem(self.Vehiculos, "")
        self.Servicios = QtWidgets.QWidget()
        self.Servicios.setGeometry(QtCore.QRect(0, 0, 91, 100))
        self.Servicios.setObjectName("Servicios")
        self.BotonCrearS = QtWidgets.QPushButton(self.Servicios)
        self.BotonCrearS.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.BotonCrearS.setObjectName("BotonCrearS")
        self.BotonBorrarS = QtWidgets.QPushButton(self.Servicios)
        self.BotonBorrarS.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.BotonBorrarS.setObjectName("BotonBorrarS")
        self.BotonListarS = QtWidgets.QPushButton(self.Servicios)
        self.BotonListarS.setGeometry(QtCore.QRect(0, 70, 91, 23))
        self.BotonListarS.setObjectName("BotonListarS")
        self.toolBox.addItem(self.Servicios, "")
        self.MostarFactura = QtWidgets.QPushButton(self.centralwidget)
        self.MostarFactura.setGeometry(QtCore.QRect(550, 30, 121, 23))
        self.MostarFactura.setObjectName("MostarFactura")
        self.BuscarFactura = QtWidgets.QPushButton(self.centralwidget)
        self.BuscarFactura.setGeometry(QtCore.QRect(550, 70, 121, 23))
        self.BuscarFactura.setObjectName("BuscarFactura")
        self.TablaFacturas = QtWidgets.QTableWidget(self.centralwidget)
        self.TablaFacturas.setGeometry(QtCore.QRect(290, 10, 256, 481))
        self.TablaFacturas.setObjectName("TablaFacturas")
        self.TablaFacturas.setColumnCount(0)
        self.TablaFacturas.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BotonBorrarC.setText(_translate("MainWindow", "Borrar Cliente"))
        self.BotonCrearC.setText(_translate("MainWindow", "Crear Cliente"))
        self.BotonListarC.setText(_translate("MainWindow", "Listar Datos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Clientes), _translate("MainWindow", "Clientes"))
        self.BotonCrearV.setText(_translate("MainWindow", "Crear Vehiculo"))
        self.BotonBorrarV.setText(_translate("MainWindow", "Borrar Vehiculo"))
        self.BotonListarV.setText(_translate("MainWindow", "Listar Datos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Vehiculos), _translate("MainWindow", "Vehiculos"))
        self.BotonCrearS.setText(_translate("MainWindow", "Crear Servicio"))
        self.BotonBorrarS.setText(_translate("MainWindow", "Borrar Servicio"))
        self.BotonListarS.setText(_translate("MainWindow", "Listar Datos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Servicios), _translate("MainWindow", "Servicios"))
        self.MostarFactura.setText(_translate("MainWindow", "Mostar Factura"))
        self.BuscarFactura.setText(_translate("MainWindow", "Buscar Factura"))
