# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):
    
    #def loadData(self):
    #    connection = sqlite3.connect('facturas.txt')
    #    #query = 'Select * from nombre'
    #    result = Clients.get_all()
    #    self.tableWidget.setRowCount(0)
    #    for row_number, row_data in enumerate(result):
    #        self.tableWidget.insertRow(row_number)
    #        for column_number, data in enumerate(row_data):
    #            self.tableWidget.setItem(row_number,column_number, QtWidgets.QTableWidgetItem(str(data)))
                
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(40, 20, 91, 181))
        self.toolBox.setObjectName("toolBox")
        self.Clientes = QtWidgets.QWidget()
        self.Clientes.setGeometry(QtCore.QRect(0, 0, 91, 100))
        self.Clientes.setObjectName("Clientes")
        self.BotonBorrarC = QtWidgets.QPushButton(self.Clientes)
        self.BotonBorrarC.setGeometry(QtCore.QRect(0, 30, 91, 23))
        self.BotonBorrarC.setObjectName("BotonBorrarC")
        self.BotonCrearC = QtWidgets.QPushButton(self.Clientes)
        self.BotonCrearC.setGeometry(QtCore.QRect(0, 0, 91, 23))
        self.BotonCrearC.setObjectName("BotonCrearC")
        self.BotonListarC = QtWidgets.QPushButton(self.Clientes)
        self.BotonListarC.setGeometry(QtCore.QRect(0, 60, 91, 23))
        self.BotonListarC.setObjectName("BotonListarC")
        self.toolBox.addItem(self.Clientes, "")
        self.Vehiculos = QtWidgets.QWidget()
        self.Vehiculos.setGeometry(QtCore.QRect(0, 0, 91, 100))
        self.Vehiculos.setObjectName("Vehiculos")
        self.BotonCrearV = QtWidgets.QPushButton(self.Vehiculos)
        self.BotonCrearV.setGeometry(QtCore.QRect(0, 0, 91, 23))
        self.BotonCrearV.setObjectName("BotonCrearV")
        self.BotonBorrarV = QtWidgets.QPushButton(self.Vehiculos)
        self.BotonBorrarV.setGeometry(QtCore.QRect(0, 30, 91, 23))
        self.BotonBorrarV.setObjectName("BotonBorrarV")
        self.BotonListarV = QtWidgets.QPushButton(self.Vehiculos)
        self.BotonListarV.setGeometry(QtCore.QRect(0, 60, 91, 23))
        self.BotonListarV.setObjectName("BotonListarV")
        self.toolBox.addItem(self.Vehiculos, "")
        self.Servicios = QtWidgets.QWidget()
        self.Servicios.setGeometry(QtCore.QRect(0, 0, 91, 100))
        self.Servicios.setObjectName("Servicios")
        self.BotonCrearS = QtWidgets.QPushButton(self.Servicios)
        self.BotonCrearS.setGeometry(QtCore.QRect(0, 0, 91, 23))
        self.BotonCrearS.setObjectName("BotonCrearS")
        self.BotonListarS = QtWidgets.QPushButton(self.Servicios)
        self.BotonListarS.setGeometry(QtCore.QRect(0, 60, 91, 23))
        self.BotonListarS.setObjectName("BotonListarS")
        self.BotonBorrarS = QtWidgets.QPushButton(self.Servicios)
        self.BotonBorrarS.setGeometry(QtCore.QRect(0, 30, 91, 23))
        self.BotonBorrarS.setObjectName("BotonBorrarS")
        self.toolBox.addItem(self.Servicios, "")
        self.MostarFactura = QtWidgets.QPushButton(self.centralwidget)
        self.MostarFactura.setGeometry(QtCore.QRect(190, 180, 121, 23))
        self.MostarFactura.setObjectName("MostarFactura")
        self.BuscarFactura = QtWidgets.QPushButton(self.centralwidget)
        self.BuscarFactura.setGeometry(QtCore.QRect(340, 180, 121, 23))
        self.BuscarFactura.setObjectName("BuscarFactura")
        self.TablaFacturas = QtWidgets.QTableWidget(self.centralwidget)
        self.TablaFacturas.setGeometry(QtCore.QRect(35, 220, 661, 301))
        self.TablaFacturas.setObjectName("TablaFacturas")
        self.TablaFacturas.setColumnCount(21)
        self.TablaFacturas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaFacturas.setHorizontalHeaderItem(20, item)
        self.CrearFactura = QtWidgets.QPushButton(self.centralwidget)
        self.CrearFactura.setGeometry(QtCore.QRect(500, 180, 121, 23))
        self.CrearFactura.setObjectName("CrearFactura")
        self.CargarFacturas = QtWidgets.QPushButton(self.centralwidget)
        self.CargarFacturas.setGeometry(QtCore.QRect(344, 120, 111, 23))
        self.CargarFacturas.setObjectName("CargarFacturas")
        #self.CargarFacturas.clicked.connect(self.loadData)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BotonBorrarC.setText(_translate("MainWindow", "Borrar Cliente"))
        self.BotonCrearC.setText(_translate("MainWindow", "Crear Cliente"))
        self.BotonListarC.setText(_translate("MainWindow", "Listar Datos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Clientes), _translate("MainWindow", "Clientes"))
        self.BotonCrearV.setText(_translate("MainWindow", "Crear Vehiculo"))
        self.BotonBorrarV.setText(_translate("MainWindow", "Borrar Vehiculo"))
        self.BotonListarV.setText(_translate("MainWindow", "Listar Datos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Vehiculos), _translate("MainWindow", "Vehiculos"))
        self.BotonCrearS.setText(_translate("MainWindow", "Crear Servicio"))
        self.BotonListarS.setText(_translate("MainWindow", "Listar Datos"))
        self.BotonBorrarS.setText(_translate("MainWindow", "Borrar Servicio"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Servicios), _translate("MainWindow", "Servicios"))
        self.MostarFactura.setText(_translate("MainWindow", "Mostar Factura"))
        self.BuscarFactura.setText(_translate("MainWindow", "Buscar Factura"))
        item = self.TablaFacturas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No. Factura"))
        item = self.TablaFacturas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID Cliente"))
        item = self.TablaFacturas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Servicio"))
        item = self.TablaFacturas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Apellido"))
        item = self.TablaFacturas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dirección"))
        item = self.TablaFacturas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Teléfono"))
        item = self.TablaFacturas.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ciudad"))
        item = self.TablaFacturas.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Placa"))
        item = self.TablaFacturas.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Marca"))
        item = self.TablaFacturas.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Modelo"))
        item = self.TablaFacturas.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.TablaFacturas.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Cilindrada"))
        item = self.TablaFacturas.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Color"))
        item = self.TablaFacturas.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Tipo de uso"))
        item = self.TablaFacturas.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "No. Pasajeros"))
        item = self.TablaFacturas.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "No.Chasis"))
        item = self.TablaFacturas.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.TablaFacturas.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Codigo Servicio"))
        item = self.TablaFacturas.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Precio por Hora"))
        item = self.TablaFacturas.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Tiempo"))
        item = self.TablaFacturas.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Total"))
        self.CrearFactura.setText(_translate("MainWindow", "Crear Factura"))
        self.CargarFacturas.setText(_translate("MainWindow", "Cargar Facturas"))

