# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaVehiculo.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from vehicles import Vehicles


class Ui_VentanaVehiculos(object):
    def setupUi(self, VentanaVehiculo):
        VentanaVehiculo.setObjectName("VentanaVehiculo")
        VentanaVehiculo.resize(576, 688)
        self.centralwidget = QtWidgets.QWidget(VentanaVehiculo)
        self.centralwidget.setObjectName("centralwidget")
        self.IngresarMarca = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarMarca.setGeometry(QtCore.QRect(30, 100, 351, 31))
        self.IngresarMarca.setObjectName("IngresarMarca")
        self.IngresarColor = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarColor.setGeometry(QtCore.QRect(30, 280, 351, 31))
        self.IngresarColor.setObjectName("IngresarColor")
        self.AceptarInfoV = QtWidgets.QPushButton(self.centralwidget)
        self.AceptarInfoV.setGeometry(QtCore.QRect(390, 620, 75, 23))
        self.AceptarInfoV.setObjectName("AceptarInfoV")
        self.Placa = QtWidgets.QLabel(self.centralwidget)
        self.Placa.setGeometry(QtCore.QRect(30, 10, 101, 31))
        self.Placa.setObjectName("Placa")
        self.IngresarPlaca = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarPlaca.setGeometry(QtCore.QRect(30, 40, 351, 31))
        self.IngresarPlaca.setObjectName("IngresarPlaca")
        self.TipoServicio = QtWidgets.QLabel(self.centralwidget)
        self.TipoServicio.setGeometry(QtCore.QRect(30, 310, 241, 31))
        self.TipoServicio.setObjectName("TipoServicio")
        self.Marca = QtWidgets.QLabel(self.centralwidget)
        self.Marca.setGeometry(QtCore.QRect(30, 70, 91, 31))
        self.Marca.setObjectName("Marca")
        self.IngresarCilindraje = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarCilindraje.setGeometry(QtCore.QRect(30, 220, 351, 31))
        self.IngresarCilindraje.setObjectName("IngresarCilindraje")
        self.CancelarInfoV = QtWidgets.QPushButton(self.centralwidget)
        self.CancelarInfoV.setGeometry(QtCore.QRect(480, 620, 75, 23))
        self.CancelarInfoV.setObjectName("CancelarInfoV")
        self.IngresarModelo = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarModelo.setGeometry(QtCore.QRect(30, 160, 351, 31))
        self.IngresarModelo.setObjectName("IngresarModelo")
        self.IngresarTipoServicio = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarTipoServicio.setGeometry(QtCore.QRect(30, 340, 351, 31))
        self.IngresarTipoServicio.setObjectName("IngresarTipoServicio")
        self.Color = QtWidgets.QLabel(self.centralwidget)
        self.Color.setGeometry(QtCore.QRect(30, 250, 101, 31))
        self.Color.setObjectName("Color")
        self.Modelo = QtWidgets.QLabel(self.centralwidget)
        self.Modelo.setGeometry(QtCore.QRect(30, 130, 71, 31))
        self.Modelo.setObjectName("Modelo")
        self.Cilindraje = QtWidgets.QLabel(self.centralwidget)
        self.Cilindraje.setGeometry(QtCore.QRect(30, 190, 71, 31))
        self.Cilindraje.setObjectName("Cilindraje")
        self.Pasajeros = QtWidgets.QLabel(self.centralwidget)
        self.Pasajeros.setGeometry(QtCore.QRect(30, 430, 91, 31))
        self.Pasajeros.setObjectName("Pasajeros")
        self.IngresarCombustible = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarCombustible.setGeometry(QtCore.QRect(30, 400, 351, 31))
        self.IngresarCombustible.setObjectName("IngresarCombustible")
        self.Combustible = QtWidgets.QLabel(self.centralwidget)
        self.Combustible.setGeometry(QtCore.QRect(30, 370, 111, 31))
        self.Combustible.setObjectName("Combustible")
        self.Motor = QtWidgets.QLabel(self.centralwidget)
        self.Motor.setGeometry(QtCore.QRect(30, 550, 71, 31))
        self.Motor.setObjectName("Motor")
        self.textEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_9.setGeometry(QtCore.QRect(30, 580, 351, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.Chasis = QtWidgets.QLabel(self.centralwidget)
        self.Chasis.setGeometry(QtCore.QRect(30, 490, 101, 31))
        self.Chasis.setObjectName("Chasis")
        self.IngresarChasis = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarChasis.setGeometry(QtCore.QRect(30, 520, 351, 31))
        self.IngresarChasis.setObjectName("IngresarChasis")
        self.IngresarPasajeros = QtWidgets.QTextEdit(self.centralwidget)
        self.IngresarPasajeros.setGeometry(QtCore.QRect(30, 460, 351, 31))
        self.IngresarPasajeros.setObjectName("IngresarPasajeros")
        self.retranslateUi(VentanaVehiculo)
        self.CancelarInfoV.clicked.connect(VentanaVehiculo.close)
        QtCore.QMetaObject.connectSlotsByName(VentanaVehiculo)
        VentanaVehiculo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaVehiculo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 21))
        self.menubar.setObjectName("menubar")
        VentanaVehiculo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaVehiculo)
        self.statusbar.setObjectName("statusbar")
        VentanaVehiculo.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaVehiculo)
        self.AceptarInfoV.clicked.connect(self.insert1)
        self.AceptarInfoV.clicked.connect(VentanaVehiculo.close)
        QtCore.QMetaObject.connectSlotsByName(VentanaVehiculo)

        self.retranslateUi(VentanaVehiculo)
        self.AceptarInfoV.clicked.connect(self.IngresarPlaca.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarMarca.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarModelo.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarCilindraje.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarColor.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarTipoServicio.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarCombustible.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarPasajeros.selectAll)
        self.AceptarInfoV.clicked.connect(self.IngresarChasis.selectAll)
        self.AceptarInfoV.clicked.connect(self.textEdit_9.selectAll)
        QtCore.QMetaObject.connectSlotsByName(VentanaVehiculo)

    def retranslateUi(self, VentanaVehiculo):
        _translate = QtCore.QCoreApplication.translate
        VentanaVehiculo.setWindowTitle(_translate("VentanaVehiculo", "MainWindow"))
        self.AceptarInfoV.setText(_translate("VentanaVehiculo", "Aceptar"))
        self.Placa.setText(_translate("VentanaVehiculo", "No. de placa"))
        self.TipoServicio.setText(_translate("VentanaVehiculo", "Tipo que servicio que realiza: publico/particular"))
        self.Marca.setText(_translate("VentanaVehiculo", "Maca del Vehiculo"))
        self.CancelarInfoV.setText(_translate("VentanaVehiculo", "Cancelar"))
        self.Color.setText(_translate("VentanaVehiculo", "Color"))
        self.Modelo.setText(_translate("VentanaVehiculo", "Modelo"))
        self.Cilindraje.setText(_translate("VentanaVehiculo", "Cilindraje"))
        self.Pasajeros.setText(_translate("VentanaVehiculo", "No. de pasajeros"))
        self.Combustible.setText(_translate("VentanaVehiculo", "Tipo de combustible"))
        self.Motor.setText(_translate("VentanaVehiculo", "No. de motor"))
        self.Chasis.setText(_translate("VentanaVehiculo", "No. de chasis"))

    def insert1(self, VentanaVehiculo):
        data = []
        data.append(self.IngresarPlaca.toPlainText())
        data.append(self.IngresarMarca.toPlainText())
        data.append(self.IngresarModelo.toPlainText())
        data.append(self.IngresarCilindraje.toPlainText())
        data.append(self.IngresarColor.toPlainText())
        data.append(self.IngresarTipoServicio.toPlainText())
        data.append(self.IngresarCombustible.toPlainText())
        data.append(self.IngresarPasajeros.toPlainText())
        data.append(self.IngresarChasis.toPlainText())
        data.append(self.textEdit_9.toPlainText())
        vehicles = Vehicles()
        vehicles.insert2(data)