# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Delete(object):
    def setupUi(self, Delete):
        Delete.setObjectName("Delete")
        Delete.resize(401, 175)
        self.centralwidget = QtWidgets.QWidget(Delete)
        self.centralwidget.setObjectName("centralwidget")
        self.ConfirmarBorrarV = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmarBorrarV.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.ConfirmarBorrarV.setObjectName("ConfirmarBorrarV")
        self.UniqueProp = QtWidgets.QTextEdit(self.centralwidget)
        self.UniqueProp.setGeometry(QtCore.QRect(20, 90, 351, 21))
        self.UniqueProp.setObjectName("UniqueProp")
        self.CancelarBorrarV = QtWidgets.QPushButton(self.centralwidget)
        self.CancelarBorrarV.setGeometry(QtCore.QRect(100, 120, 75, 23))
        self.CancelarBorrarV.setObjectName("CancelarBorrarV")
        self.TxtID = QtWidgets.QLabel(self.centralwidget)
        self.TxtID.setGeometry(QtCore.QRect(20, 60, 131, 31))
        self.TxtID.setObjectName("TxtID")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(20, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        Delete.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Delete)
        self.statusbar.setObjectName("statusbar")
        Delete.setStatusBar(self.statusbar)

        self.retranslateUi(Delete)
        self.ConfirmarBorrarV.clicked.connect(self.UniqueProp.selectAll)
        QtCore.QMetaObject.connectSlotsByName(Delete)

    def retranslateUi(self, Delete):
        _translate = QtCore.QCoreApplication.translate
        Delete.setWindowTitle(_translate("Delete", "Delete"))
        self.ConfirmarBorrarV.setText(_translate("Delete", "Borrar"))
        self.CancelarBorrarV.setText(_translate("Delete", "Cancelar"))
        self.TxtID.setText(_translate("Delete", "Propiedad unica"))
        self.Title.setText(_translate("Delete", "Delete action"))
