# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListarVehiculos.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListarVehiculos(object):
    def setupUi(self, ListarVehiculos):
        ListarVehiculos.setObjectName("ListarVehiculos")
        ListarVehiculos.resize(606, 541)
        self.centralwidget = QtWidgets.QWidget(ListarVehiculos)
        self.centralwidget.setObjectName("centralwidget")
        self.Combustible = QtWidgets.QPushButton(self.centralwidget)
        self.Combustible.setGeometry(QtCore.QRect(500, 300, 75, 23))
        self.Combustible.setObjectName("Combustible")
        self.Motor = QtWidgets.QPushButton(self.centralwidget)
        self.Motor.setGeometry(QtCore.QRect(500, 430, 75, 23))
        self.Motor.setObjectName("Motor")
        self.CerrarLista = QtWidgets.QPushButton(self.centralwidget)
        self.CerrarLista.setGeometry(QtCore.QRect(500, 470, 75, 23))
        self.CerrarLista.setObjectName("CerrarLista")
        self.Marca = QtWidgets.QPushButton(self.centralwidget)
        self.Marca.setGeometry(QtCore.QRect(500, 100, 75, 23))
        self.Marca.setObjectName("Marca")
        self.DatosVehiculo = QtWidgets.QLabel(self.centralwidget)
        self.DatosVehiculo.setGeometry(QtCore.QRect(500, 10, 111, 51))
        self.DatosVehiculo.setObjectName("DatosVehiculo")
        self.NoPlaca = QtWidgets.QPushButton(self.centralwidget)
        self.NoPlaca.setGeometry(QtCore.QRect(500, 60, 75, 23))
        self.NoPlaca.setObjectName("NoPlaca")
        self.Chasis = QtWidgets.QPushButton(self.centralwidget)
        self.Chasis.setGeometry(QtCore.QRect(500, 380, 75, 23))
        self.Chasis.setObjectName("Chasis")
        self.TipoServicio = QtWidgets.QPushButton(self.centralwidget)
        self.TipoServicio.setGeometry(QtCore.QRect(500, 260, 81, 23))
        self.TipoServicio.setObjectName("TipoServicio")
        self.Pasajeros = QtWidgets.QPushButton(self.centralwidget)
        self.Pasajeros.setGeometry(QtCore.QRect(500, 340, 75, 23))
        self.Pasajeros.setObjectName("Pasajeros")
        self.Cilindraje = QtWidgets.QPushButton(self.centralwidget)
        self.Cilindraje.setGeometry(QtCore.QRect(500, 180, 75, 23))
        self.Cilindraje.setObjectName("Cilindraje")
        self.Modelo = QtWidgets.QPushButton(self.centralwidget)
        self.Modelo.setGeometry(QtCore.QRect(500, 140, 75, 23))
        self.Modelo.setObjectName("Modelo")
        self.Color = QtWidgets.QPushButton(self.centralwidget)
        self.Color.setGeometry(QtCore.QRect(500, 220, 75, 23))
        self.Color.setObjectName("Color")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 461, 401))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 459, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 461, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.retranslateUi(ListarVehiculos)
        self.CerrarLista.clicked.connect(ListarVehiculos.close)
        QtCore.QMetaObject.connectSlotsByName(ListarVehiculos)
        ListarVehiculos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ListarVehiculos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 21))
        self.menubar.setObjectName("menubar")
        ListarVehiculos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ListarVehiculos)
        self.statusbar.setObjectName("statusbar")
        ListarVehiculos.setStatusBar(self.statusbar)

        self.retranslateUi(ListarVehiculos)
        QtCore.QMetaObject.connectSlotsByName(ListarVehiculos)

    def retranslateUi(self, ListarVehiculos):
        _translate = QtCore.QCoreApplication.translate
        ListarVehiculos.setWindowTitle(_translate("ListarVehiculos", "ListarVehiculos"))
        self.Combustible.setText(_translate("ListarVehiculos", "Combustible"))
        self.Motor.setText(_translate("ListarVehiculos", "Motor"))
        self.CerrarLista.setText(_translate("ListarVehiculos", "Cerrar"))
        self.Marca.setText(_translate("ListarVehiculos", "Marca"))
        self.DatosVehiculo.setText(_translate("ListarVehiculos", "Ordenar Datos:"))
        self.NoPlaca.setText(_translate("ListarVehiculos", "No de Placa"))
        self.Chasis.setText(_translate("ListarVehiculos", "Chasis"))
        self.TipoServicio.setText(_translate("ListarVehiculos", "Tipo de servicio"))
        self.Pasajeros.setText(_translate("ListarVehiculos", "Pasajeros"))
        self.Cilindraje.setText(_translate("ListarVehiculos", "Cilindraje"))
        self.Modelo.setText(_translate("ListarVehiculos", "Modelo"))
        self.Color.setText(_translate("ListarVehiculos", "Color"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ListarVehiculos", "Placa"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ListarVehiculos", "Marca"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ListarVehiculos", "Modelo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ListarVehiculos", "Cilindraje"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ListarVehiculos", "Color"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ListarVehiculos", "Tipo de uso"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ListarVehiculos", "Combustible"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ListarVehiculos", "No. Pasajeros"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ListarVehiculos", "No. Chasis"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ListarVehiculos", "No. Motor"))
